### ISSUE TITLE
[FEAT] 홈 - 나의 오늘 연결하기

### ISSUE THREAD

**Issue by naerim** [tea-kkeul/Tea-KKeul-iOS#44]
## Issue

홈 - 나의 오늘 section 버튼들 연결해보기!

## Todo

- [x] 나뭇잎 상태 연결하기
- [x] 현재 날짜 연결하기
- [x] 내 몸 상태 태그 연결하기
