### ISSUE TITLE
[FEAT] Magazine 프로토 구현

### ISSUE THREAD

**Issue by yunkyung-Hwang** [tea-kkeul/Tea-KKeul-iOS#8]
## Issue
매거진 뷰 프로토 구현

## Todo

- [x] magazine collectionView 구현
- [x] cell 데이터 추가
- [x] cell 데이터 적용
